controller_manager:
    ros__parameters:
        update_rate: 15  # Hz
        diagnostic_period: 1

        forward_position_controller:
            type: forward_command_controller/ForwardCommandController

        joint_state_controller:
            type: joint_state_controller/JointStateController

        position_trajectory_controller:
            type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
    ros__parameters:
        joints: [J11,J12,J13,J14,J15,J16,J17,J18,J19,J21,J22,J23,J24,J25,J26,J27,J28,J29]
        interface_name: effort

position_trajectory_controller:
    ros__parameters:
        joints: [J11,J12,J13,J14,J15,J16,J17,J18,J19,J21,J22,J23,J24,J25,J26,J27,J28,J29]
        interface_name: position

lss_realtime:
    ros__parameters:
        update_rate: 15  # Hz
        diagnostic_period: 1

imu:
    ros__parameters:
        port: /dev/ttyAMA4
        frame_id: imu_link
        frequency: 30.0
        self_manage: true
        use_magnetometer: true

        angular_velocity_stdev: 0.01
        linear_acceleration_stdev: 0.0015
        magnetic_field_stdev: 0.0000005
        orientation_stdev: 0.000001
        # these calibration values need to be determined on a per-device basis.
        calibration/accelerometer_offset: [3, -89, -41]
        calibration/magnetometer_offset: [-7146, 5376, 143]
        calibration/gyroscope_offset: [-2, 2, 0]
        calibration/accelerometer_radius: 1000
        calibration/magnetometer_radius: 608
