robot_dynamics:
    ros__parameters:
        frequency: 20.0
        model_state_frequency: 10.0
        self_manage: true
        leg_support_distance: 0.06
        joint_states: joint_states
        odometry: /odom_raw
        joint_controller: position_trajectory_controller
        joint_names: [J11,J12,J13,J14,J15,J16,J17,J18,J19,J21,J22,J23,J24,J25,J26,J27,J28,J29]
        chain0: "[leg] base_link => r_sole"
        chain1: "[leg] base_link => l_sole"

