humanoid_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - J11
      - J12
      - J13
      - J14
      - J15
      - J16
      - J17
      - J18
      - J19
      - J21
      - J22
      - J23
      - J24
      - J25
      - J26
      - J27
      - J28
      - J29
    write_op_modes:
      - J11
      - J12
      - J13
      - J14
      - J15
      - J16
      - J17
      - J18
      - J19
      - J21
      - J22
      - J23
      - J24
      - J25
      - J26
      - J27
      - J28
      - J29
    state_publish_rate: 25
    action_monitor_rate: 20
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 5

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
    publish_rate: 20
